import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderDesktop from "./components/header-desktop/header";
import MobileHeader from "./components/header-mobile/header";
import { Nunito } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const nunito = Nunito({subsets: ["latin"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={nunito.className}>
        <HeaderDesktop/>
        {children}
        <MobileHeader/>
        </body>
    </html>
  );
}
